break: `converter toBool` -> `template toPyBool`
Rationale:
- This converter is invasive.
- So invasive is it as it causes defining `repr`
for some type like `PyList` failed tracking to `system/repr_v2`

The snippet of error msg: ```lib/system/repr_v2.nim(65, 18)
Error: ambiguous call;
both dollars.$(x: bool) [proc declared in lib/system/dollars.nim(37, 6)]
and dollars.$(x: uint64) [proc declared in lib/system/dollars.nim(24, 6)]
match for: (uint8)
```